### ISSUE TITLE
specifying constant arguments inline not working

### ISSUE THREAD

**Issue by Sohalt** [retro/graphql-builder#1]
I cannot specify an argument directly in the query (i.e. not via a variable).
For example a query of the form:
```graphql
query Foo {
  bar(baz:{quux:42}) {
    xyzzy
  }
}
```
breaks.

If I send the query with curl it works just fine.

**Comment by retro** [comment]
I've released `0.1.4` which fixes this bug.

**Comment by Sohalt** [comment]
That was quick. Thank you!
