### ISSUE TITLE
enum not properly parsed/generated

### ISSUE THREAD

**Issue by scgilardi** [retro/graphql-builder#15]
I'm using [Hasura](https://hasura.io/). It allows an `order_by` argument to order results. The `order_by` value is an object containing a key that is the field to order by and a value is one of several enumerated values including `asc` and `desc`.

Hasura's graphql server expects the value to be a GraphQL enum and fails if it is a quoted string.

This query works when run within Hasura's built-in GraphiQL:

```
query LoadHistory {
  history(limit: 10000, order_by: {date: asc}) {
    id: history_id
    date
  }
}
```

When I run that query through `graphql-builder.parser/parse`, the result shows this for the arguments to `history`:

```
      [{:node-type :argument,
       :argument-name "limit",
       :value 10000,
       :variable-name nil,
       :value-type :integer}
      {:node-type :argument,
       :argument-name "order_by",
       :value [:object-value [{:name "date", :value "asc"}]],
       :variable-name nil,
       :value-type :object}],
```

It appears not to capture the fact that the value "asc" needs to be an enum, not a string. Perhaps it's because it's a value nested within an object. When I run the query via graphql-builder, it passes along the quoted string "asc" and the query returns an error: "enum expected". 

Here is what GraphiQL returns when I simulate that query syntax:
```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.history.args.order_by[0].date",
        "code": "validation-failed"
      },
      "message": "expecting an enum"
    }
  ]
}
```

- It would be nice for graphql-builder to support this query;

- Would it be possible to work around this by making that value a query variable? I don't see how to suggest to the parser that the value should be an enum in that case (where it seems it might be easy if it were a `String!` or  `Int!` variable).

**Comment by retro** [comment]
@scgilardi I _think_ that a short term fix would be to pass "asc" as a variable. I'll check what needs to be done to provide real support in the meantime

**Comment by Cukac** [comment]
@retro 
another example
```
query AssignableTerminals {
  terminals(first: 100, filter: {assignability: ASSIGNABLE}) {
    edges {
      node {
        id
        terminalVersion
        deviceId
        availabilityState
      }
    }
  }
}
```
