### ISSUE TITLE
Use graphql with file-contents instead of file names

### ISSUE THREAD

**Issue by Luke1298** [retro/graphql-builder#25]
In order to get shadow cljs to hot reload with `defgraphql` it would be nice if there was another macro that did all but the "read file" step of `defgraphql` -- or alternatively a flag or something. 

(Shadow cljs supports a "rc/inline" which handles setting up a watch on a file, but it also reads said file)

Happy to make PR if you think it's a good idea!

**Comment by Luke1298** [comment]
Hmmm... Actually I played around with this-- it seems like: `https://github.com/alumbra/alumbra.parser` would first have to have a method to handle a string rather than a file.

**Comment by Luke1298** [comment]
Turns out putting a list of: (rc/inline "operation1.graphql") will actually cause a namespace reload anyway. So this is probably completely unnecessary.

**Comment by retro** [comment]
@Luke1298 what is `rc` namespace in this case?

**Comment by heneryville** [comment]
It is `shaodw.resource`.

```clojure
(ns my-stuff
(:require 
   [graphql-builder.parser :refer-macros [defgraphql]]
   [shadow.resource :as rc]))
   
(rc/inline "operations.graphql")
(defgraphql gql-queries "src/graphql_ops/operations.graphql")
(def gql-query-map (gql/query-map gql-queries {:inline-fragments true}))
```

**Comment by Luke1298** [comment]
@retro ^^ What @heneryville said... Sorry for the lack of response.
