### ISSUE TITLE
goog.nodeGlobalRequire is not a function

### ISSUE THREAD

**Issue by danielneal** [retro/graphql-builder#4]
Hey, 
This is unlikely to be high on your priority list, but when trying to use this library in react native, I get the error "goog.nodeGlobalRequire" is not a function. 

It this something you've seen?
As far as I can tell it seems to be down to including the `cuerdas` library.

**Comment by retro** [comment]
Hey @danielneal Are you still experiencing this problem? If so, can you create a minimal breaking example? I'm using the lib in multiple react-native projects without any issues

**Comment by danielneal** [comment]
Hey, 

Yes I'm still experiencing this problem - but only in certain cases. 

I made a minimal repro (https://github.com/danielneal/graphql-builder-repro) and noticed the problem only happens when the `:target` is set to `:nodejs`, which I needed to do to get reagent 0.8 to work (see https://github.com/drapanjanas/re-natal/issues/128)

I found a way (in dev) to get reagent 0.8 *and* graphql-builder to work - 
by setting `:npm-deps` to `false`, and removing `:target :nodejs` 

Note: if using figwheel, this commit is needed https://github.com/bhauman/lein-figwheel/pull/678 otherwise `:npm-deps false` doesn't pass the figwheel compiler option validation.

**Comment by danielneal** [comment]
Dang! I did a production build (`optimization: advanced`) with reagent 0.8 and graphql-builder, and `:npm-deps false` and it didn't work - failed trying to find `create-react-class`.

So the thorny problem seems to be: to use reagent 0.8 (and react 16) requires setting `:target :nodejs`, but to use this library successfully (because of the cuerdas calls that depend on the js library xregexp) seems to requires `:target :default`.

**Comment by retro** [comment]
@danielneal I've pushed new version (0.1.6) that doesn't use cuerdas anymore. Can you check if this one works for you?

**Comment by retro** [comment]
@danielneal I've tried to run your repro example, and it seems to be working now

**Comment by danielneal** [comment]
@retro aw that's great thanks for the amazingly fast turnaround!
