### ISSUE TITLE
returned graphql query is invalid when using variables

### ISSUE THREAD

**Issue by kurt-o-sys** [retro/graphql-builder#6]
When I have file like this:
```
query findUsers ($starts_with: String) {allUsers (filter: {name_starts_with: $starts_with}) {id name}}
```
Fetching the query (from the cljs repl) returns:
```
((get-in queries [:query :find-users]))
{:graphql
 {:operationName "findUsers",
  :query
  "query findUsers($starts_with: String) {\n  allUsers(filter: { name_starts_with: {:variable-name \"starts_with\"} }) {\n    id\n    name\n  }\n}",
  :variables {}}, 
 :unpack #object[cljs$core$identity]}
```

The returned query contains `:variable-name`. When I use that query in a project directly calling graphql, I get:
```
GraphQLError {message: "Syntax Error: Expected Name, found :", locations: Array(1), path: undefined, nodes: undefined, source: Source, …}
```

![image](https://user-images.githubusercontent.com/2430465/36633265-830e9a8e-1992-11e8-9eff-736220c6d561.png)

Where JSON expects a valid variable name, there's a cljs keyword. 
How do I solve this?

**Comment by retro** [comment]
@kurt-o-sys Can you try making you variable names camel cased? I'm using camel cased variables without any problems, but I'm not sure if that's the problem

**Comment by kurt-o-sys** [comment]
Nope, doesn't help. I have no issues with passing variables to mutations. Maybe it's because of the map passed to the filter?

`src/graphql/user.graphql`:
```
fragment user on User {id name email auth {id roles groups permissions}}

query allUsers {allUsers {...user}}

query findUsers ($startsWith: String) {
  allUsers: allUsers(filter: {name_starts_with: $startsWith}) {
    id
    name}}
```

code:
```
(defgraphql graphql-queries
  "src/graphql/booking.graphql"
  "src/graphql/user.graphql"
  "src/graphql/service.graphql")

(def queries (query-map graphql-queries))
```

repl:
```
((get-in queries [:query :find-users]))
{:graphql
 {:operationName "findUsers",
  :query
  "query findUsers($startsWith: String) {\n  allUsers: allUsers(filter: { name_starts_with: {:variable-name \"startsWith\"} }) {\n    id\n    name\n  }\n}",
  :variables {}}, 
 :unpack #object[cljs$core$identity]}
```

**Comment by retro** [comment]
@kurt-o-sys You are correct. I'm not sure if this is something that can be made to work without significant effort. Can you pass your whole filter as a variable instead?

**Comment by kurt-o-sys** [comment]
works perfect, thx!
