### ISSUE TITLE
swallowing (silently) compilation error?

### ISSUE THREAD

**Issue by lwhorton** [retro/graphql-builder#9]
Kudos for providing this lib, we've found it quite useful. 

I noticed there's a sneaky case where, when compiling my cljs (via shadow-cljs), the compiler hangs forever and just heats up my CPU fan. Here's an example gql file that would cause a hang:
```
query MyQuery {
  foo {
    bar {
       a
       b
  }
}
```
Notice the missing closing brace on `bar { .. }`. I'm fairly certain that the parse error is getting swallowed up inside this library, but I'm not positive. Is this something you have run into before? I wanted to make a quick note of this here just in case someone else runs into the same issue.

**Comment by retro** [comment]
@lwhorton Unfortunatelly this is an issue in the underlying library. I think that instaparse can't parse the file correctly and it ends in an infinite loop. I'm not sure if there's a way to fix it or prevent it from the "outside"
